name: Call on_master

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  call-workflow:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/on_master.yml
    permissions:
      contents: write