name: on_master

on:
  workflow_call:


jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: echo
        run: |
          echo "hello" 