name: on_master

on:
  workflow_call:

env:
  SERVICE_IMAGE_REPO: "maryamdrv/my-simple-image"
  SERVICE_IMAGE_TAG: 1.3

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: echo
        run: |
          echo "hello" 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: maryamdrv
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check if image tag exists
        id: check_service_tag
        run: |
          if docker manifest inspect "$SERVICE_IMAGE_REPO:$SERVICE_IMAGE_TAG" > /dev/null 2>&1; then
            echo "image tag already exists"
            exit 1
          else
            echo "image tag does not exist"
          fi
      - name: Build new Docker image
        id: build_base
        run: |
          ./build_docker_image.sh

      - name: Push service Docker image
        run: |
          docker push $SERVICE_IMAGE_REPO:$SERVICE_IMAGE_TAG   
          
      - name: Get service Docker image digest
        id: id_get_service_digest
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $SERVICE_IMAGE_REPO:$SERVICE_IMAGE_TAG)
          if [ -z "$DIGEST" ]; then
            echo "Failed to retrieve digest for $SERVICE_IMAGE_REPO:$SERVICE_IMAGE_TAG"
            exit 1
          fi
          echo "service_digest=$DIGEST" >> $GITHUB_OUTPUT
          
      - name: Update file with image digest
        run: |
          cd $GITHUB_WORKSPACE
          FILE_PATH=service-image-digest.txt
          SERVICE_IMAGE_DIGEST=${{ steps.id_get_service_digest.outputs.service_digest }}
          if [ ! -f $FILE_PATH ]; then
            touch $FILE_PATH
          fi
          echo "$SERVICE_IMAGE_DIGEST" >> $FILE_PATH

      - name: Commit and push image digest
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          branch_name="update-image-digest"
          git checkout -b $branch_name

          git add service-image-digest.txt
          git commit -m "Update Docker image digest [ci skip]"

          git pull --rebase origin master
          git push origin $branch_name