name: on_master

on:
  workflow_call:


jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: echo
        run: |
          echo "hello" 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: maryamdrv
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check if image tag exists
        id: check_service_tag
        run: |
          if docker manifest inspect "bash:3.2.57-alpine3.20" > /dev/null 2>&1; then
            echo "image tag already exists"
            exit 1
          else
            echo "image tag does not exist"
          fi
